approve_by_comment: true
approve_regex: ^((A|a)pproved|:shipit:( )?|:\+1:( )?)$
reject_regex: ^((R|r)ejected|:shipit:( )?|:-1:)$
reset_on_push: false
author_approval: ignored
reviewers:
  members:
  - kronos-pbrideau
  - svigneux
  - nvanheuverzwijn
  name: default
  required: 1
